### PR TITLE
Krisjand

### PR DESCRIPTION
**Pull request by krisjand**
I've added a theta parameter to the 'power_law_gauss' type of the Cl-prior. This theta parameter works like the existing beta parameter for the 'gauss' Cl-prior type. This way the 'power_law_gauss' type actually becomes a product of the 'power_law' and 'gauss' type Cl-priors.

There are a few additions and changes to the writing/reading routines to HDF/fits, also for the other Cl-prior types (like 'gauss').

The new parameter is COMP_CL_DEFAULT_THETA_{T,E,B}&& = real dp ( >= 0 ), only valid (and looked for) if COMP_CL_TYPE&& = 'power_law_gauss'

The default parameter files have been updated accordingly. In addition I've added the COMP_INIT_FOR_HDF&& parameter to the main parameter file as this is switched on/off on a more regular basis

Finally, in commander.f90, line 227 have been changed so that the TOD sampling first happen on sample 2 (same as spectral parameters). This is to ensure that if a component is not initialized from chain, then Commander samples the components first. The users that only initialize from chain is free to change this, but I think that sampling TOD from sample 2 should be the default.

### CODE REVIEW

**Comment by dncnwtts** [comment]
Is it possible to make there be a parameter that asks which sample to start TOD analysis from? I think we changed it in the WMAP development just so we wouldn't have to go through several Gibbs iterations before getting to the TOD analysis

**Comment by krisjand** [comment]
No, I do not think there is a parameter that decides what sample to start the TOD sampling from, only how often to do the TOD sampling (NUM_GIBBS_STEPS_PER_TOD_SAMPLE)

**Comment by krisjand** [comment]
I mean, making a new parameter just for this, i.e. when to start TOD sampling, should be simple enough.

**Comment by dncnwtts** [comment]
It's not a huge deal, as you say anyone could just make that edit, but I have seen that particular number change around a bit lately... Otherwise I have no problems, would like to get someone else's feedback before merging though

**Pull request merged**
